name: main
on:
  workflow_dispatch:
jobs:
  imp1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 10
          echo "ok"
  imp2:
    runs-on: ubuntu-latest
    needs: imp1
    steps:
      - run: |
          sleep 10
          echo "ok 2"
  imp3:
    runs-on: ubuntu-latest
    needs: imp1
    steps:
      - run: |
          sleep 10
          echo "ok 2"